"""
Grade-based skill profiles for player evaluation
Each grade represents a weighted combination of relevant statistics
for skill-based assessment (0-100 scale)
"""

GRADE_ATTRIBUTES = {
    "Crossing": {
        "display_name": "Crossing Grade",
        "description": "Overall crossing ability combining volume, accuracy, and danger. Measures ability to deliver quality balls into the box from wide areas.",
        "components": [
            {"stat": "Crosses per 90", "weight": 0.30, "use_percentile": True},
            {"stat": "Accurate crosses, %", "weight": 0.25, "use_percentile": True},
            {
                "stat": "Deep completed crosses per 90",
                "weight": 0.20,
                "use_percentile": True,
            },
            {
                "stat": "Crosses to goalie box per 90",
                "weight": 0.15,
                "use_percentile": True,
            },
            {
                "stat": "Accurate crosses from left flank, %",
                "weight": 0.05,
                "use_percentile": True,
            },
            {
                "stat": "Accurate crosses from right flank, %",
                "weight": 0.05,
                "use_percentile": True,
            },
        ],
        "icon": "🎯",
    },
    "Passing": {
        "display_name": "Passing Grade",
        "description": "Overall passing quality combining accuracy, progression, and chance creation. Measures ability to move the ball effectively and create opportunities.",
        "components": [
            {"stat": "Accurate passes, %", "weight": 0.20, "use_percentile": True},
            {
                "stat": "Progressive passes per 90",
                "weight": 0.18,
                "use_percentile": True,
            },
            {
                "stat": "Passes to final third per 90",
                "weight": 0.15,
                "use_percentile": True,
            },
            {"stat": "Key passes per 90", "weight": 0.12, "use_percentile": True},
            {
                "stat": "Accurate short / medium passes, %",
                "weight": 0.12,
                "use_percentile": True,
            },
            {
                "stat": "Passes to penalty area per 90",
                "weight": 0.10,
                "use_percentile": True,
            },
            {"stat": "Accurate long passes, %", "weight": 0.08, "use_percentile": True},
            {"stat": "Smart passes per 90", "weight": 0.05, "use_percentile": True},
        ],
        "icon": "🎨",
    },
    "Shooting": {
        "display_name": "Shooting Grade",
        "description": "Overall shooting ability combining volume, accuracy, and efficiency. Measures ability to convert chances and test the goalkeeper.",
        "components": [
            {"stat": "Goals per 90", "weight": 0.25, "use_percentile": True},
            {"stat": "xG per 90", "weight": 0.20, "use_percentile": True},
            {"stat": "Shots on target, %", "weight": 0.18, "use_percentile": True},
            {"stat": "Goal conversion, %", "weight": 0.15, "use_percentile": True},
            {"stat": "Shots per 90", "weight": 0.12, "use_percentile": True},
            {
                "stat": "Non-penalty goals per 90",
                "weight": 0.10,
                "use_percentile": True,
            },
        ],
        "icon": "⚽",
    },
    "TackleInterception": {
        "display_name": "Ball-Winning Grade",
        "description": "Defensive ball-winning ability combining tackles and interceptions. Measures ability to regain possession through defensive actions.",
        "components": [
            {"stat": "PAdj Interceptions", "weight": 0.25, "use_percentile": True},
            {
                "stat": "Successful defensive actions per 90",
                "weight": 0.20,
                "use_percentile": True,
            },
            {"stat": "Interceptions per 90", "weight": 0.18, "use_percentile": True},
            {"stat": "PAdj Sliding tackles", "weight": 0.15, "use_percentile": True},
            {"stat": "Sliding tackles per 90", "weight": 0.12, "use_percentile": True},
            {"stat": "Shots blocked per 90", "weight": 0.10, "use_percentile": True},
        ],
        "icon": "⚔️",
    },
    "Duel": {
        "display_name": "Duel Grade",
        "description": "Overall dueling ability across ground and aerial situations. Measures success rate and volume in physical contests.",
        "components": [
            {"stat": "Duels won, %", "weight": 0.30, "use_percentile": True},
            {"stat": "Defensive duels won, %", "weight": 0.20, "use_percentile": True},
            {"stat": "Aerial duels won, %", "weight": 0.20, "use_percentile": True},
            {"stat": "Offensive duels won, %", "weight": 0.15, "use_percentile": True},
            {"stat": "Duels per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Aerial duels per 90", "weight": 0.05, "use_percentile": True},
        ],
        "icon": "💪",
    },
    "Dribble": {
        "display_name": "Dribble Grade",
        "description": "Ball carrying and take-on ability. Measures skill in beating opponents 1v1 and progressing with the ball.",
        "components": [
            {"stat": "Successful dribbles, %", "weight": 0.30, "use_percentile": True},
            {"stat": "Dribbles per 90", "weight": 0.20, "use_percentile": True},
            {"stat": "Progressive runs per 90", "weight": 0.18, "use_percentile": True},
            {"stat": "Offensive duels won, %", "weight": 0.15, "use_percentile": True},
            {"stat": "Accelerations per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Offensive duels per 90", "weight": 0.07, "use_percentile": True},
        ],
        "icon": "🏃",
    },
    "Forward": {
        "display_name": "Forward Grade",
        "description": "Overall forward ability combining volume, accuracy, and efficiency. Measures ability to convert chances and test the goalkeeper.",
        "components": [
            {"stat": "xG per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "xA per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Shots per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Touches in box per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Non-penalty goals per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Dribbles per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Key passes per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "Shot assists per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Progressive runs per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Progressive passes per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Smart passes per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Passes to penalty area per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Goal conversion, %", "weight": 0.03, "use_percentile": True},
            {"stat": "Offensive duels won, %", "weight": 0.03, "use_percentile": True},
            {"stat": "Successful dribbles, %", "weight": 0.04, "use_percentile": True},
            {"stat": "Crosses per 90", "weight": 0.02, "use_percentile": True},
            {"stat": "Accurate crosses, %", "weight": 0.01, "use_percentile": True},
            {
                "stat": "Deep completed crosses per 90",
                "weight": 0.02,
                "use_percentile": True,
            },
        ],
        "icon": "",
    },
    "Fullback": {
        "display_name": "Fullback Grade",
        "description": "Overall ability evaluated for a fullback including defending, ball progression, crossing and overlap runs.",
        "components": [
            {"stat": "Crosses per 90", "weight": 0.14, "use_percentile": True},
            {"stat": "Accurate crosses, %", "weight": 0.13, "use_percentile": True},
            {"stat": "Defensive duels per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "PAdj Interceptions", "weight": 0.05, "use_percentile": True},
            {"stat": "PAdj Sliding tackles", "weight": 0.05, "use_percentile": True},
            {"stat": "Tackles per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Successful defensive actions per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Progressive runs per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Deep completed crosses per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Dribbles per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Accelerations per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Aerial duels per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Deep completions per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Progressive passes per 90", "weight": 0.04, "use_percentile": True},
            {"stat": "Passes to final third per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Long passes per 90", "weight": 0.02, "use_percentile": True},
            {"stat": "Interceptions per 90", "weight": 0.02, "use_percentile": True},
            {"stat": "Forward passes per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Aerial duels won, %", "weight": 0.03, "use_percentile": True},
            {"stat": "Received passes per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Received long passes per 90", "weight": 0.02, "use_percentile": True},
        ],
        "icon": "",
    },
    "Defender": {
        "display_name": "Defender Grade",
        "description": "Overall ability evaluated for a Defender Defensive Attribute.",
        "components": [
            {"stat": "Defensive duels per 90", "weight": 0.09, "use_percentile": True},
            {"stat": "Successful defensive actions per 90", "weight": 0.10, "use_percentile": True},
            {"stat": "PAdj Interceptions", "weight": 0.10, "use_percentile": True},
            {"stat": "PAdj Sliding tackles", "weight": 0.10, "use_percentile": True},
            {"stat": "Aerial duels per 90", "weight": 0.07, "use_percentile": True},
            {"stat": "Defensive duels won, %", "weight": 0.07, "use_percentile": True},
            {"stat": "Duels won, %", "weight": 0.05, "use_percentile": True},
            {"stat": "Aerial duels won, %", "weight": 0.05, "use_percentile": True},
            {"stat": "Progressive runs per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Progressive passes per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Received passes per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Tackles per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Deep completions per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Passes to final third per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Forward passes per 90", "weight": 0.03, "use_percentile": True},
            {"stat": "Accurate progressive passes, %", "weight": 0.03, "use_percentile": True},
            {"stat": "Accurate passes, %", "weight": 0.03, "use_percentile": True},
            {"stat": "Long passes per 90", "weight": 0.02, "use_percentile": True},
            {"stat": "Interceptions per 90", "weight": 0.02, "use_percentile": True},
        ],
        "icon": "",
    },
    # ========== GOALKEEPER GRADES ==========
    "Goalkeeper": {
        "display_name": "Goalkeeper Grade",
        "description": "Overall goalkeeper ability across shot stopping, distribution, aerial command, and sweeping. Balanced assessment suitable for comparing GKs across all styles.",
        "components": [
            {"stat": "Save rate, %",                      "weight": 0.25, "use_percentile": True},
            {"stat": "Prevented goals per 90",            "weight": 0.20, "use_percentile": True},
            {"stat": "Conceded goals per 90",             "weight": -0.15, "use_percentile": True},
            {"stat": "Aerial duels won, %",               "weight": 0.10, "use_percentile": True},
            {"stat": "Exits per 90",                      "weight": 0.10, "use_percentile": True},
            {"stat": "Accurate long passes, %",           "weight": 0.10, "use_percentile": True},
            {"stat": "Accurate passes, %",                "weight": 0.10, "use_percentile": True},
            {"stat": "Back passes received as GK per 90", "weight": 0.05, "use_percentile": True},
            {"stat": "Aerial duels per 90",               "weight": 0.05, "use_percentile": True},
        ],
        "icon": "🧤",
    },
    "GKShotStopping": {
        "display_name": "Shot-Stopping Grade",
        "description": "Pure shot-stopping ability focused on save rate and goal prevention relative to expected goals against. Higher score = more goals saved than expected.",
        "components": [
            {"stat": "Save rate, %",           "weight": 0.40, "use_percentile": True},
            {"stat": "Prevented goals per 90", "weight": 0.35, "use_percentile": True},
            {"stat": "Conceded goals per 90",  "weight": -0.25, "use_percentile": True},
        ],
        "icon": "🥅",
    },
    "GKDistribution": {
        "display_name": "Distribution Grade",
        "description": "Passing and distribution quality from the back — both short and long pass accuracy, volume of progressive delivery, and involvement in build-up via back passes.",
        "components": [
            {"stat": "Accurate long passes, %",           "weight": 0.30, "use_percentile": True},
            {"stat": "Accurate passes, %",                "weight": 0.25, "use_percentile": True},
            {"stat": "Long passes per 90",                "weight": 0.20, "use_percentile": True},
            {"stat": "Progressive passes per 90",         "weight": 0.15, "use_percentile": True},
            {"stat": "Back passes received as GK per 90", "weight": 0.10, "use_percentile": True},
        ],
        "icon": "🎯",
    },
    "GKSweeper": {
        "display_name": "Sweeper-Keeper Grade",
        "description": "Proactive off-line ability — exits to deal with through balls, aerial dominance outside the area, and contribution to pressing/high-line systems.",
        "components": [
            {"stat": "Exits per 90",              "weight": 0.40, "use_percentile": True},
            {"stat": "Aerial duels per 90",       "weight": 0.25, "use_percentile": True},
            {"stat": "Aerial duels won, %",       "weight": 0.20, "use_percentile": True},
            {"stat": "Progressive passes per 90", "weight": 0.15, "use_percentile": True},
        ],
        "icon": "🧹",
    },
}
